// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/int_array.proto

package ru.java.hse.message;

public final class IntArrayProtos {
  private IntArrayProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IntArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IntArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>repeated int32 array = 2;</code>
     * @return A list containing the array.
     */
    java.util.List<java.lang.Integer> getArrayList();
    /**
     * <code>repeated int32 array = 2;</code>
     * @return The count of array.
     */
    int getArrayCount();
    /**
     * <code>repeated int32 array = 2;</code>
     * @param index The index of the element to return.
     * @return The array at the given index.
     */
    int getArray(int index);
  }
  /**
   * Protobuf type {@code IntArray}
   */
  public static final class IntArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IntArray)
      IntArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IntArray.newBuilder() to construct.
    private IntArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IntArray() {
      array_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IntArray();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IntArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                array_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              array_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                array_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                array_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          array_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IntArrayProtos.internal_static_IntArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IntArrayProtos.internal_static_IntArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IntArrayProtos.IntArray.class, IntArrayProtos.IntArray.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int ARRAY_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList array_;
    /**
     * <code>repeated int32 array = 2;</code>
     * @return A list containing the array.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getArrayList() {
      return array_;
    }
    /**
     * <code>repeated int32 array = 2;</code>
     * @return The count of array.
     */
    public int getArrayCount() {
      return array_.size();
    }
    /**
     * <code>repeated int32 array = 2;</code>
     * @param index The index of the element to return.
     * @return The array at the given index.
     */
    public int getArray(int index) {
      return array_.getInt(index);
    }
    private int arrayMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (getArrayList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(arrayMemoizedSerializedSize);
      }
      for (int i = 0; i < array_.size(); i++) {
        output.writeInt32NoTag(array_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      {
        int messageSize = 0;
        for (int i = 0; i < array_.size(); i++) {
          messageSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(array_.getInt(i));
        }
        size += messageSize;
        if (!getArrayList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(messageSize);
        }
        arrayMemoizedSerializedSize = messageSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IntArrayProtos.IntArray)) {
        return super.equals(obj);
      }
      IntArrayProtos.IntArray other = (IntArrayProtos.IntArray) obj;

      if (getId()
          != other.getId()) return false;
      if (!getArrayList()
          .equals(other.getArrayList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      if (getArrayCount() > 0) {
        hash = (37 * hash) + ARRAY_FIELD_NUMBER;
        hash = (53 * hash) + getArrayList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IntArrayProtos.IntArray parseFrom(
        java.nio.ByteBuffer message)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(message);
    }
    public static IntArrayProtos.IntArray parseFrom(
        java.nio.ByteBuffer message,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(message, extensionRegistry);
    }
    public static IntArrayProtos.IntArray parseFrom(
        com.google.protobuf.ByteString message)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(message);
    }
    public static IntArrayProtos.IntArray parseFrom(
        com.google.protobuf.ByteString message,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(message, extensionRegistry);
    }
    public static IntArrayProtos.IntArray parseFrom(byte[] message)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(message);
    }
    public static IntArrayProtos.IntArray parseFrom(
        byte[] message,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(message, extensionRegistry);
    }
    public static IntArrayProtos.IntArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IntArrayProtos.IntArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IntArrayProtos.IntArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IntArrayProtos.IntArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IntArrayProtos.IntArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IntArrayProtos.IntArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IntArrayProtos.IntArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IntArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IntArray)
        IntArrayProtos.IntArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IntArrayProtos.internal_static_IntArray_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IntArrayProtos.internal_static_IntArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IntArrayProtos.IntArray.class, IntArrayProtos.IntArray.Builder.class);
      }

      // Construct using IntArrayProtos.IntArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        array_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IntArrayProtos.internal_static_IntArray_descriptor;
      }

      @java.lang.Override
      public IntArrayProtos.IntArray getDefaultInstanceForType() {
        return IntArrayProtos.IntArray.getDefaultInstance();
      }

      @java.lang.Override
      public IntArrayProtos.IntArray build() {
        IntArrayProtos.IntArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public IntArrayProtos.IntArray buildPartial() {
        IntArrayProtos.IntArray result = new IntArrayProtos.IntArray(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        if (((bitField0_ & 0x00000001) != 0)) {
          array_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.array_ = array_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IntArrayProtos.IntArray) {
          return mergeFrom((IntArrayProtos.IntArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IntArrayProtos.IntArray other) {
        if (other == IntArrayProtos.IntArray.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.array_.isEmpty()) {
          if (array_.isEmpty()) {
            array_ = other.array_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureArrayIsMutable();
            array_.addAll(other.array_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IntArrayProtos.IntArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IntArrayProtos.IntArray) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList array_ = emptyIntList();
      private void ensureArrayIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          array_ = mutableCopy(array_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 array = 2;</code>
       * @return A list containing the array.
       */
      public java.util.List<java.lang.Integer>
          getArrayList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(array_) : array_;
      }
      /**
       * <code>repeated int32 array = 2;</code>
       * @return The count of array.
       */
      public int getArrayCount() {
        return array_.size();
      }
      /**
       * <code>repeated int32 array = 2;</code>
       * @param index The index of the element to return.
       * @return The array at the given index.
       */
      public int getArray(int index) {
        return array_.getInt(index);
      }
      /**
       * <code>repeated int32 array = 2;</code>
       * @param index The index to set the value at.
       * @param value The array to set.
       * @return This builder for chaining.
       */
      public Builder setArray(
          int index, int value) {
        ensureArrayIsMutable();
        array_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 array = 2;</code>
       * @param value The array to add.
       * @return This builder for chaining.
       */
      public Builder addArray(int value) {
        ensureArrayIsMutable();
        array_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 array = 2;</code>
       * @param values The array to add.
       * @return This builder for chaining.
       */
      public Builder addAllArray(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureArrayIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, array_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 array = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearArray() {
        array_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IntArray)
    }

    // @@protoc_insertion_point(class_scope:IntArray)
    private static final IntArrayProtos.IntArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IntArrayProtos.IntArray();
    }

    public static IntArrayProtos.IntArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IntArray>
        PARSER = new com.google.protobuf.AbstractParser<IntArray>() {
      @java.lang.Override
      public IntArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new IntArray(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IntArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IntArray> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public IntArrayProtos.IntArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IntArray_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IntArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptormessage = {
      "\n\031resources/int_array.proto\"%\n\010IntArray\022" +
      "\n\n\002id\030\001 \001(\005\022\r\n\005array\030\002 \003(\005B\035\n\013ru.hse.dat" +
      "aB\016IntArrayProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptormessage,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IntArray_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IntArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IntArray_descriptor,
        new java.lang.String[] { "Id", "Array", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
